export namespace Configuracion {
  export const hashNotificacion = "Pr0yectHashSec"
  export const mensajeSolicitudCreada = "Su solicitud para el trabajo academico fue creada exitosamente con los siguientes datos: "
  export const urlCorreo = "http://localhost:5000/correo"
  export const urlMensajeTexto = "http://localhost:5000/sms"
  export const urlGetProponente = "http://localhost:3000/proponente-trabajos/"
  export const urlGetJurado = "http://localhost:3002/jurados/"
  export const asuntoCreacionSolicitud = "Su solicitud se creó satisfactoriamente"
  export const destinoArg = "destino"
  export const asuntoArg = "asunto"
  export const mensajeArg = "mensaje"
  export const hashArg = "hash"
  export const asuntoInvitacionEvaluacion = "Invitacion a evaluar un trabajo academico"
  export const mensajeInvitacionEvaluacion = "Usted fue seleccionado para evaluar un trabajo academico, usted puede elegir si aceptar la invitacion o rechazarla <br/>Estos son los datos del trabajo academico: "
  export const asuntoAceptarSolicitud = "Un jurado acaba de aceptar su solicitud"
  export const mensajeAceptarSolicitud = "Felicidades, un jurado acepto evaluar su solicitud, pronto podra saber el resultado de su evaluacion. <br/>Detalles: "
  export const asuntoRechazarSolicitud = "Un jurado acaba de rechazar su solicitud"
  export const mensajeRechazarSolicitud = "Lo sentimos, un jurado rechazo evaluar su solicitud, estaremos invitando a otro jurado a evaluar su solicitud. <br/>Detalles: "
  export const asuntoRecordatorio = "Tiene solicitudes pendientes por evaluar"
  export const mensajeRecordatorio = "Vemos que desde hace tiempo acepto una solicitud y no la ha evaluado, queremos recordarle que ingrese al sistema y las evalue cuando pueda. <br/><br/>Muchas gracias."
}
